Get the CI into a working state.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -54,7 +54,7 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkoutv2.3.4
+        uses: actions/checkout@v2.3.4
         with:
           fetch-depth: 0
 
@@ -67,21 +67,47 @@ jobs:
           python -m pip install --upgrade pip wheel setuptools
           python -m pip install jsonschema[format]
 
-      - name: Run checks
+      - name: Run validations against the jsonchema
         id: checks
+        continue-on-error: true
         run: |
           .github/scripts/sentinel.py ${{ needs.json_files.outputs.jfiles }} > msg.txt 2>err.txt
           if [[ -s "msg.txt" ]]; then
-            echo "::set-output name=has_report::yes"
+            echo "::set-output name=has_report::true"
             body=$(<msg.txt)
             body="${body//'%'/'%25'/}"
             body="${body//$'\n'/'%0A'}"
             body="${body//$'\r'/'%0D'}"
             echo "::set-output name=body::$body"
           else
-            echo "::set-output name=has_report::no"
+            echo "::set-output name=has_report::false"
           fi
-          [[ -s "err.txt" ]] && echo "::set-output name=breakage::1"
+          if [[ -s "err.txt" ]]; then
+            echo "::set-output name=breakage::true"
+            echo "::group::Error during validation."
+            echo "::warning File err.txt exists. Sentinel broke."
+            echo "::endgroup::"
+            exit 1
+          fi
+
+      - if: ${{ steps.checks.outputs.breakage == 'true' }}
+        name: Report Sentinel breakage
+        uses: peter-evans/create-issue-from-file@v3
+        with:
+          title: "Sentinel broke in PR #${{ github.event.pull_request.number }}"
+          content-filepath: ./err.txt
+          labels: |
+            sentinel
+            automated issue
+            bug
+          assignees: bicobus
+
+      - uses: actions/upload-artifact@v2
+        with:
+          name: sentinel_output
+          path: |
+            err.txt
+            msg.txt
 
       - name: Find Comment
         uses: peter-evans/find-comment@v1
@@ -91,7 +117,7 @@ jobs:
           comment-author: 'github-actions[bot]'
           body-includes: "Blip Blop I'm a robot"
 
-      - if: ${{ steps.checks.output.has_report == "yes"}}
+      - if: ${{ steps.checks.outputs.has_report == 'true' }}
         name: Create comment on PR
         uses: peter-evans/create-or-update-comment@v1.4.5
         with:
@@ -103,15 +129,3 @@ jobs:
             ${{ steps.checks.outputs.body }}
             --
             This comment will automatically be updated as you update your pull request.
-
-      - if: ${{ failure() && steps.checks.outputs.breakage }}
-        name: Report Sentinel breakage
-        uses: peter-evans/create-issue-from-filev3
-        with:
-          title: "Sentinel broke in PR #${{ github.event.pull_request.number }}"
-          content-filepath: ./err.txt
-          labels: |
-            sentinel
-            automated issue
-            bug
-          assignees: bicobus
